routes/admin.php
<?php

use App\Http\Controllers\Admin\ClientController;
use App\Http\Controllers\Admin\ClientCredentialController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AjaxController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ReportsController;
use App\Http\Controllers\SectorsController;
use App\Http\Controllers\SlidersController;
use App\Http\Controllers\ArticlesController;
use App\Http\Controllers\VeyeController; 
use App\Http\Controllers\EnquiryController;
use App\Http\Controllers\ReportsCategoryController;
use App\Http\Controllers\RecommendationController;
use App\Http\Controllers\AsxCodeController;
use App\Http\Controllers\CompaniesController;
use App\Http\Controllers\SubscriptionsController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\SubMenuController;
use App\Http\Controllers\ProductsController;
use App\Http\Controllers\StockAdvisoryController;
use App\Http\Controllers\ExportExcelController;
use App\Http\Controllers\ExportdataMonthsaleController;
use App\Http\Controllers\AddPageController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\WebinarController;
use App\Http\Controllers\TestimonialsController;
use App\Http\Controllers\ClientSubscriptionsController;
use App\Http\Controllers\DaytodayMailController;
use App\Http\Controllers\SendMailController;
use App\Http\Controllers\PersonalRecommendationController;
use App\Http\Controllers\AllReportsController;
use App\Http\Controllers\SubscriptionReportController;
use App\Http\Controllers\WatchListController;
use App\Http\Controllers\EmailTemplateController;
use App\Http\Controllers\PrivacyPolicyController;
use App\Http\Controllers\FsgPolicyController;
use App\Http\Controllers\TermConditionsController;
use App\Http\Controllers\AboutUsPolicyController;
use App\Http\Controllers\MenuesController;
use App\Http\Controllers\FooterController;
use App\Http\Controllers\InvoicePrintController;
use App\Http\Controllers\ReportMonthController;
use App\Http\Controllers\EditorialController;
use App\Http\Controllers\PaymentTypeController;
use App\Http\Controllers\ClientTypeController;
use App\Http\Controllers\AddPopupController;
use App\Http\Controllers\AsxTypeController;
use App\Http\Controllers\AddMonthsController;
use App\Http\Controllers\TestManagementController;
use App\Http\Controllers\FaqController;
use App\Http\Controllers\BannerController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\LogoController;
use App\Http\Controllers\HomesController;
use App\Http\Controllers\LeadController;
use App\Http\Controllers\PaymentTransactionsController;
use Illuminate\Support\Facades\Auth;

Route::group(['prefix' => 'admin'], function () {
  Auth::routes();
});
Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function () {
  Route::get('home', [HomeController::class, 'index'])->name('home');
  Route::get('home-deashboard', [HomeController::class, 'freeReportEnq'])->name('dashboard.freeReportEnq');
  Route::get('delete-enq/{id}', [HomeController::class, 'destroy'])->name('dashboard.destroy');
  Route::resource('roles', RoleController::class)->except(['destroy']);
  Route::get('roles/delete/{id}', [RoleController::class, 'destroy'])->name('roles.destroy');

  Route::resource('users', UserController::class)->except(['destroy']);
  Route::get('user/destroy/{id}', [UserController::class, 'destroy'])->name('users.destroy');

  Route::resource('permission', PermissionController::class);

  Route::get('ajax/populate-state/{country}/{state?}', [AjaxController::class, 'populateState'])->name('ajax.populate-state');

  // payment-transactions //
  Route::resource('payment-transactions', PaymentTransactionsController::class)->except(['destroy']);
  Route::get('payment-transactions/destroy/{id}', [PaymentTransactionsController::class, 'destroy'])->name('payment-transactions.destroy');

  // Products //
  Route::resource('products', ProductsController::class)->except(['destroy']);
  Route::get('products/destroy/{id}', [ProductsController::class, 'destroy'])->name('products.destroy');


  //Homes //
  Route::resource('homes', HomesController::class)->except(['destroy']);
  Route::get('homes/destroy/{id}', [HomesController::class, 'destroy'])->name('homes.destroy');
 
  //Reports // 
  Route::resource('reports', ReportsController::class)->except(['destroy']);
  Route::get('reports/destroy/{id}', [ReportsController::class, 'destroy'])->name('reports.destroy');

  //subscription_report //
Route::resource('subscription-report', SubscriptionReportController::class)->except(['destroy']);
  Route::get('subscription-report/destroy/{id}', [SubscriptionReportController::class, 'destroy'])->name('subscription-report.destroy');

  //Reports Category //
  Route::resource('reports-category', ReportsCategoryController::class)->except(['destroy']);
  Route::get('reports-category/destroy/{id}', [ReportsCategoryController::class, 'destroy'])->name('reports-category.destroy');


   //Page Category //
  Route::resource('category', CategoryController::class)->except(['destroy']);
  Route::get('category/destroy/{id}', [CategoryController::class, 'destroy'])->name('category.destroy');


  //What Clients Say About Us? ///testmanagement //
  Route::resource('testmanagement', TestManagementController::class)->except(['destroy']);
  Route::get('testmanagement/destroy/{id}', [TestManagementController::class, 'destroy'])->name('testmanagement.destroy');

  //Recommendation //
  Route::resource('recommendations', RecommendationController::class)->except(['destroy']);
  Route::get('recommendations/destroy/{id}', [RecommendationController::class, 'destroy'])->name('recommendations.destroy');

  //PersonalRecommendation //
  Route::resource('personalrecommendations', PersonalRecommendationController::class)->except(['destroy']);
  Route::get('personalrecommendations/destroy/{id}', [PersonalRecommendationController::class, 'destroy'])->name('personalrecommendations.destroy');

  //ASX Code //
  Route::resource('asx-code', AsxCodeController::class)->except(['destroy']);
  Route::get('asx-code/destroy/{id}', [AsxCodeController::class, 'destroy'])->name('asx-code.destroy');


  //Payment Type //
  Route::resource('payment-type', PaymentTypeController::class)->except(['destroy']);
  Route::get('payment-type/destroy/{id}', [PaymentTypeController::class, 'destroy'])->name('payment-type.destroy');

  //Country//
  Route::resource('country', CountryController::class)->except(['destroy']);
  Route::get('country/destroy/{id}', [CountryController::class, 'destroy'])->name('country.destroy');

  //Asx Type //
  Route::resource('asx-type', AsxTypeController::class)->except(['destroy']);
  Route::get('asx-type/destroy/{id}', [AsxTypeController::class, 'destroy'])->name('asx-type.destroy');

  //Client Type //
  Route::resource('client-type', ClientTypeController::class)->except(['destroy']);
  Route::get('client-type/destroy/{id}', [ClientTypeController::class, 'destroy'])->name('client-type.destroy');

  //Add Months //
  Route::resource('add-months', AddMonthsController::class)->except(['destroy']);
  Route::get('add-months/destroy/{id}', [AddMonthsController::class, 'destroy'])->name('add-months.destroy');

  //Add popup //
  Route::resource('add-popup', AddPopupController::class)->except(['destroy']);
  Route::get('add-popup/destroy/{id}', [AddPopupController::class, 'destroy'])->name('add-popup.destroy');


  //Menu //
  Route::resource('menu', MenuController::class)->except(['destroy']);
  Route::get('menu/destroy/{id}', [MenuController::class, 'destroy'])->name('menu.destroy');

  //Sub Menu //
  Route::resource('sub-menu', SubMenuController::class)->except(['destroy']);
  Route::get('sub-menu/destroy/{id}', [SubMenuController::class, 'destroy'])->name('sub-menu.destroy');

  /// Sector ///
  Route::resource('sector', SectorsController::class)->except(['destroy']);
  Route::get('sector/destroy/{id}', [SectorsController::class, 'destroy'])->name('sector.destroy');

  /// Logo ///
  Route::resource('logo', LogoController::class)->except(['destroy']);
  Route::get('logo/destroy/{id}', [LogoController::class, 'destroy'])->name('logo.destroy');

  /// banner ///
  Route::resource('banner', BannerController::class)->except(['destroy']);
  Route::get('banner/destroy/{id}', [BannerController::class, 'destroy'])->name('banner.destroy');

  /// Sliders ///
  Route::resource('sliders', SlidersController::class)->except(['destroy']);
  Route::get('sliders/destroy/{id}', [SlidersController::class, 'destroy'])->name('sliders.destroy');

  /// Subscribe Page ///
  Route::resource('subscriptions', SubscriptionsController::class)->except(['destroy']);
  Route::get('subscriptions/destroy/{id}', [SubscriptionsController::class, 'destroy'])->name('subscriptions.destroy');

  /// Client Subscibtion ///
  Route::resource('subscription', ClientSubscriptionsController::class)->except(['destroy']);
  Route::get('subscription/destroy/{id}', [ClientSubscriptionsController::class, 'destroy'])->name('subscription.destroy');

  /// Day to day Mail ///
  Route::resource('daytodaymail', DaytodayMailController::class)->except(['destroy']);
  Route::get('daytodaymail/destroy/{id}', [DaytodayMailController::class, 'destroy'])->name('daytodaymail.destroy');

  /// Send Mail ///
  Route::resource('sendmail', SendMailController::class)->except(['destroy']);
  Route::get('sendmail/destroy/{id}', [SendMailController::class, 'destroy'])->name('sendmail.destroy');

  /// Personal Recommendation ///
  Route::resource('personalrecommendation', PersonalRecommendationController::class)->except(['destroy']);
  Route::get('personalrecommendation/destroy/{id}', [PersonalRecommendationController::class, 'destroy'])->name('personalrecommendation.destroy');

  /// Articles ///

routes/frontend.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AjaxController;
use App\Http\Controllers\frontend\ClientsRegistrationController;
use App\Http\Controllers\frontend\HomeController;
use App\Http\Controllers\frontend\FrontendController;
use App\Http\Controllers\frontend\RegisterNoController;
use App\Http\Controllers\frontend\ContactUsController;
use App\Http\Controllers\frontend\WatchListController;
use App\Http\Controllers\Payment\PaymentController;
use Illuminate\Support\Facades\Auth;

/* 
    Clients Registration
    Dated 06-02-2023
    */

Route::get('search-company', [HomeController::class, 'search_company'])->name('search.company');
Route::get('search-company-name', [ClientsRegistrationController::class, 'company_name'])->name('searchcom.company_name');
Route::resource('registration', ClientsRegistrationController::class)->except(['destroy']);

Route::get('client-login', [ClientsRegistrationController::class, 'login'])->name('registration.login');

Route::post('client-login-match', [ClientsRegistrationController::class, 'loginMatch'])->name('registration.login.match');

Route::get('dashboard', [ClientsRegistrationController::class, 'dashboard'])->name('dashboard.home');

Route::get('forgot-password', [ClientsRegistrationController::class, 'forgotPassword'])->name('forgot.password');

Route::post('send-password-reset-link', [ClientsRegistrationController::class, 'send_pass_reset_link'])->name('reset.send_pass_reset_link');

Route::post('reset-password', [ClientsRegistrationController::class, 'resetPassword'])->name('reset.password');

Route::get('password/reset/{id}', [ClientsRegistrationController::class, 'forgotPasswordSet'])->name('password.forgotPasswordSet');

Route::get('/', [HomeController::class, 'index'])->name('index');
Route::get('404', [HomeController::class, 'pageMotFound'])->name('pagenotfound');

Route::get('search', [HomeController::class, 'search'])->name('search.report');
Route::get('search/{id}', [HomeController::class, 'sectorSearch'])->name('searchSector.report');
Route::get('sector-specific', [HomeController::class, 'sectorSpecific'])->name('sectorSpecific');
Route::get('subscribe', [HomeController::class, 'subscriptionMenu'])->name('subscriptionMenu');
//changed subscriptionMenu to subscribe
Route::get('editorial', [HomeController::class, 'editorial'])->name('editorial');
//changed subscriptionMenu to subscribe
Route::get('article/{slug}', [HomeController::class, 'article'])->name('article');
Route::get('articles', [HomeController::class, 'articles'])->name('articles');

Route::get('stock-advisory', [HomeController::class, 'stockadvisory'])->name('stockadvisory');

/// Register No ///
Route::resource('webinarfrontend-register', RegisterNoController::class);

Route::resource('contactus', ContactUsController::class);
Route::post('email_subscribe', [ContactUsController::class, 'emailSubscribe'])->name('email.subscribe');

Route::get('more-report-details', [HomeController::class, 'more_report_details'])->name('more_report_details');

Route::get('report_details/{id}', [HomeController::class, 'report_details'])->name('report_details');

Route::get('blog/{slug}', [HomeController::class, 'editorial_details'])->name('editorial-details');
Route::get('editorial-details/{slug}', [HomeController::class, 'editorial_details_blog'])->name('editorial-details_blog');

Route::get('contact-us', [HomeController::class, 'contact_us'])->name('contact_us');

Route::get('checkout', [HomeController::class, 'checkout'])->name('checkout');
Route::get('addtocart', [HomeController::class, 'addToCart'])->name('addtocart');
Route::get('removeCart', [HomeController::class, 'removeCart'])->name('removeCart');
Route::get('offer/{slug}', [HomeController::class, 'offer'])->name('offer');
Route::get('thankyou', [HomeController::class, 'thankyou'])->name('thankyou');

Route::get('editorialdetails', [HomeController::class, 'editorialdetails'])->name('editorialdetails');

//Webinar / frontend
Route::get('webinarfrontend', [HomeController::class, 'webinarfrontend'])->name('webinarfrontend');

Route::resource('update-report', FrontendController::class)->except(['destroy']);
Route::get('report/{parent}/{child?}', [FrontendController::class, 'manage_menues'])->name('manage.menues');
Route::get('pages/{parent}', [FrontendController::class, 'manage_footer'])->name('manage.footer');
Route::get('report-read-more', [FrontendController::class, 'report_read_more_nf'])->name('report.read.more.nf');
Route::get('report-read-more/{parent?}', [FrontendController::class, 'report_read_more'])->name('report.read.more');
// Auth::routes();
// Auth::routes();

// Route::post('/payment', [PaymentController::class, 'payment']);
Route::post('/payment', [PaymentController::class, 'payment'])->name('stripe.payment');
Route::post('/payment-details', [PaymentController::class, 'storeYourPaymentDetails'])->name('store.storeYourPaymentDetails');
Route::post('/store-payment-details', [PaymentController::class, 'store_payment_details'])->name('store.storePaymentDetails');

Route::post('notify', [PaymentController::class, 'notifyPayment'])->name('notify');
Route::get('cancel', [PaymentController::class, 'cancelPayment'])->name('cancel');
Route::post('return/{id}', [PaymentController::class, 'returnPayment'])->name('return');
Route::post('paypal-info', [PaymentController::class, 'paypalInfo'])->name('paypal.paypalInfo');

Route::post('your-payment-status', [PaymentController::class, 'yourPaymentStatus'])->name('yourPaymentStatus');

Route::group(['middleware' => ['auth']], function () {
    Route::resource('addwatchlist', WatchListController::class)->except(['destroy']);
    Route::get('my-watchlist', [ClientsRegistrationController::class, 'watchlist'])->name('my.watchlist');
    Route::post('create-watch-list', [WatchListController::class, 'passwordupdate'])->name('createWatchlist.store');

    Route::get('latest-buy', [ClientsRegistrationController::class, 'latestbuy'])->name('latest.buy');
    Route::get('latest-sell', [ClientsRegistrationController::class, 'latestsell'])->name('latest.sell');
    Route::get('my-email', [ClientsRegistrationController::class, 'updateEmail'])->name('my.email');
    Route::get('my-password', [ClientsRegistrationController::class, 'updatePass'])->name('my.password');
    Route::get('my-subscription', [ClientsRegistrationController::class, 'mySubscription'])->name('my.subscription');
    Route::get('my-invoice', [ClientsRegistrationController::class, 'myInvoice'])->name('my.invoice');
    Route::get('subscription-pdfs/{id}', [ClientsRegistrationController::class, 'subscriptionGeneratePDFS'])->name('my.subscriptionGeneratePDFS');

    Route::post('email-update/{id}', [ClientsRegistrationController::class, 'emailupdate'])->name('useremail.emailupdate');
    Route::post('password-update/{id}', [ClientsRegistrationController::class, 'passwordupdate'])->name('userpassword.passwordupdate');

    Route::get('user-report/{parent}/{child?}', [ClientsRegistrationController::class, 'userReports'])->name('user.reports');

    // Route::get('registration/destroy/{id}',[ClientsRegistrationController::class,'destroy'])->name('registration.destroy');

    // Route::get('privacypolicies', [FrontendController::class, 'Privacypolicies'])->name('Privacypolicies');
    // Route::get('about-us',[FrontendController::class,'about_us'])->name('about-us');


    // Route::get('terms-condition',[FrontendController::class,'terms-condition'])->name('terms-condition');
    // Route::get('about-us',[FrontendController::class,'about-us'])->name('about-us');

});

routes/web.php
<?php
use Illuminate\Support\Facades\Route;
// Route::get('/', function () {
//     return view('frontend/index');
// });

require __DIR__.'/frontend.php';

resources/views/admin/sub-menu/add.blade.php
@extends('layouts.admin')
@section('title') Add Sub Menu @endsection
@section('content')
    <div class="page-content">
        <!-- BEGIN PAGE TITLE-->
        <h1 class="page-title"> Add Report
            <small>Add Sub Menu</small>
        </h1>
        <!-- END PAGE TITLE-->
        <!-- BEGIN PAGE BAR -->
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <a href="{{route('home')}}">Dashboard</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li><span>Administrator</span><i class="fa fa-angle-right"></i></li>
                <li>
                    <a href="{{route('sub-menu.index')}}">Sub Menu</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li><span>Add</span></li>
            </ul>
            <div class="page-toolbar">
                
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 col-xs-12 col-sm-12">
                <form class="forms-sample" method="post" enctype="multipart/form-data" action="{{route('sub-menu.store')}}">
					@csrf 

                    <div class="form-group row">
                        <div class="col-lg-3">
                            <label class="col-form-label">Select Menu</label>
                        </div>
                        <div class="col-lg-8">
                        <select name="menu_id" id="" class="form-control">
                            <option value="">--Select--</option>
                            @foreach($menues as $data)
                                    <option value="{{$data->id}}">{{$data->title}}</option>
                                @endforeach
                           </select>
                            @if ($errors->has('menu_id'))
                                <span class="help-block">
                                <strong>{{ $errors->first('menu_id') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-lg-3">
                            <label class="col-form-label">Title</label>
                        </div>
                        <div class="col-lg-8">
                            <input class="form-control" name="title" type="text" placeholder="Enter title here" value="{{old('title')}}">
                            @if ($errors->has('title'))
                                <span class="help-block">
                                <strong>{{ $errors->first('title') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>

						
                    <div class="form-group row">
                        <div class="col-lg-8 offset-lg-3">
                            <button type="submit" class="btn btn-primary mr-2"><i class="fa fa-plus me-2"></i> Add</button>
                            <button class="btn btn-light" type="reset">Reset</button>
                        </div>
                    </div>
				</form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/sub-menu/edit.blade.php
@extends('layouts.admin')
@section('title') Edit Sub Menu @endsection
@section('content')
    <div class="page-content">
        <!-- BEGIN PAGE TITLE-->
        <h1 class="page-title"> Edit Sub Menu
            <small>Edit Sub Menu</small>
        </h1>
        <!-- END PAGE TITLE-->
        <!-- BEGIN PAGE BAR -->
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <a href="{{route('home')}}">Dashboard</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li><span>Administrator</span><i class="fa fa-angle-right"></i></li>
                <li>
                    <a href="{{route('sub-menu.index')}}">Sub Menu</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li><span>Edit</span></li>
            </ul>
            <div class="page-toolbar">
                
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 col-xs-12 col-sm-12">
                <form class="forms-sample" method="post" enctype="multipart/form-data" action="{{route('sub-menu.update',$user->id)}}">
                    @csrf
                    {{ method_field('PATCH') }}

                    <div class="form-group row">
                        <div class="col-lg-3">
                            <label class="col-form-label">Select Menu</label>
                        </div>
                        <div class="col-lg-8">
                        <select name="menu_id" id="" class="form-control">
                            <option value="">--Select--</option>
                            @foreach($menues as $data)
                                    <option value="{{$data->id}}" @if($data->id==$user->menu_id) selected @endif>{{$data->title}}</option>
                                @endforeach
                           </select>
                            @if ($errors->has('menu_id'))
                                <span class="help-block">
                                <strong>{{ $errors->first('menu_id') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-lg-3">
                            <label class="col-form-label">Title</label>
                        </div>
                        <div class="col-lg-8">
                            <input class="form-control" name="title" type="text" placeholder="Enter title here" value="{{$user->title}}">
                            @if ($errors->has('title'))
                                <span class="help-block">
                                <strong>{{ $errors->first('title') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                 		
                    <div class="form-group row">
                        <div class="col-lg-8 offset-lg-3">
                            <button type="submit" class="btn btn-primary mr-2">Update</button>
                            <button class="btn btn-light" type="reset">Reset</button>
                        </div>
                    </div>
				</form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/sub-menu/index.blade.php
@extends('layouts.admin')
@section('title') Manage Sub Menu @endsection
@section('head')
    <link href="{{asset('assets/global/plugins/datatables/datatables.min.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css')}}" rel="stylesheet" type="text/css" />

    <link href="{{asset('assets/global/plugins/select2/css/select2.min.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('assets/global/plugins/select2/css/select2-bootstrap.min.css')}}" rel="stylesheet" type="text/css" />
    <style>
        .select2-container{
            width: 100%!important;
        }
        .select2-search--dropdown .select2-search__field {
            width: 98%;
        }
    </style>
@endsection
@section('js')
    <script src="{{asset('assets/global/scripts/datatable.js')}}" type="text/javascript"></script>
    <script src="{{asset('assets/global/plugins/datatables/datatables.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js')}}" type="text/javascript"></script>
    <script src="{{asset('assets/global/plugins/select2/js/select2.full.min.js')}}" type="text/javascript"></script>

    <script type="text/javascript">
		$(document).ready(function(){
			$('#dataTableExample').dataTable({
					"aLengthMenu": [
						[10, 30, 50, -1],
						[10, 30, 50, "All"]
					],
					// "pagingType": "full_numbers",
					"iDisplayLength": 10,
					"language": {
						search: ""
					},
					"serverSide": true,
					"processing": true,
					"paging": true,
					"ajax":{
						url:'{{route("sub-menu.index")}}',
						data:function(e){

						}
					},
					'createdRow': function( row, data, dataIndex ) {
						$(row).attr('id', 'tr_'+data.id);
					},
					columns: [
						{ data: "sno" ,name: 'sno',searchable: false, sortable : false, visible:true},
						{ data: "menu" ,name: 'menu',searchable: false, sortable : false, visible:true},
						{ data: "title" ,name:"title"},
						{ data: "action" ,name: 'action',searchable: false, sortable : false, visible:true},
					],
                    "fnInitComplete": function (oSettings, json) {

                    }
				});

		});
    </script>
@endsection
@section('content')
    <div class="page-content">
        <!-- BEGIN PAGE TITLE-->
        <h1 class="page-title"> Manage Sub Menu
            <small>Manage Sub Menu</small>
        </h1>
        <!-- END PAGE TITLE-->
        <!-- BEGIN PAGE BAR -->
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <a href="{{route('home')}}">Dashboard</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li><span>Administrator</span><i class="fa fa-angle-right"></i></li>
                <li><span>Sub Menu</span></li>
            </ul>
            <div class="page-toolbar">
                <a class="btn btn-primary" href="{{route('sub-menu.create')}}"><i class="fa fa-plus me-2"></i> Add Sub Menu</a>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 col-xs-12 col-sm-12">
                <div>
					<table id="dataTableExample" class="table table-bordered table-striped table-responsive">
                        <thead>
                            <tr>
                                <th>Sl No</th>
                                <th>Menu</th>
                                <th>Title</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection